### ISSUE TITLE
Please provide the steps for keys and setup to use it. 

### ISSUE THREAD

**Issue by percy-g2** [joreilly/GeminiKMP#2]
I used it from https://makersuite.google.com/app/apikey but it's not working.

<img width="802" alt="Screenshot 2024-01-05 at 4 03 23 AM" src="https://github.com/joreilly/GeminiKMP/assets/4012000/f00c3a29-ae7d-4ef6-9d6c-099d7e1c9837">

@joreilly please check and help

**Comment by joreilly** [comment]
you need to add this to `local.properties` ....I'll update README to make that clearer.

```
gemini_api_key=<your_key>
```

**Comment by percy-g2** [comment]
still same issue @joreilly

**Comment by joreilly** [comment]
What's the issue you're seeing?

**Comment by percy-g2** [comment]
okay, it works now.My key was in double quote , removing the quote.
 Fixed it.

**Comment by percy-g2** [comment]
![Screenshot_1704409364](https://github.com/joreilly/GeminiKMP/assets/4012000/39611b67-3060-4d4c-a444-5170dfd3beb4)

**Comment by percy-g2** [comment]
@joreilly apologies
